apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tempo
labels:
  - pairs: { app.kubernetes.io/part-of: tempo }
resources:
  - namespace.yaml
  - web.yaml
  - gateway.yaml
  - redis.yaml
  - network-policies.yaml
  - ingress.yaml
