import { Language, translateUi } from '../../lib/i18n';

const copy: Record<string, [string, string]> = {
  'For your team': ['За вашиот тим', 'Për ekipin tuaj'],
  'Good to know': ['Добро е да знаете', 'Mirë ta dini'],
  'Check in': ['Пријава', 'Regjistrohu'],
  'Checked out': ['Одјавено', 'Dalja u regjistrua'],
  'Estimated earnings': ['Проценета заработка', 'Paga e përllogaritur'],
  'People. Time. In sync.': ['Луѓе. Време. Во ритам.', 'Njerëz. Kohë. Në harmoni.'],
  'A better rhythm for work.': ['Подобар ритам на работа.', 'Një ritëm më i mirë pune.'],
  'Your team has enough to do. Give them one simple place for shifts, hours, and pay.': ['Вашиот тим има доволно обврски. Овозможете му едно едноставно место за смени, часови и исплата.', 'Ekipi juaj ka mjaft punë. Jepini një vend të thjeshtë për turnet, orët dhe pagesat.'],
  'Explore the platform': ['Разгледајте ја платформата', 'Eksploroni platformën'],
  'Everything moves together.': ['Сè се движи заедно.', 'Gjithçka ecën së bashku.'],
  'Try the workflow': ['Испробајте го процесот', 'Provoni procesin'],
  'Interactive preview': ['Интерактивен преглед', 'Pamje ndërvepruese'],
  'A place for every person.': ['Место за секој човек.', 'Një vend për çdo person.'],
  'Put the right people in the right place. Everyone knows when to arrive and what comes next.': ['Поставете ги вистинските луѓе на вистинското место. Секој знае кога да пристигне и што следува.', 'Vendosni njerëzit e duhur në vendin e duhur. Të gjithë e dinë kur të vijnë dhe çfarë vjen më pas.'],
  'Be there. Be counted.': ['Присутни. Евидентирани.', 'Të pranishëm. Të regjistruar.'],
  'A quick scan connects the person, the place, and the time. No chasing messages at the end of the day.': ['Брзо скенирање ги поврзува човекот, местото и времето. Без барање пораки на крајот на денот.', 'Një skanim i shpejtë lidh personin, vendin dhe kohën. Pa kërkuar mesazhe në fund të ditës.'],
  'Time that adds up.': ['Време со јасна вредност.', 'Kohë që merr vlerë.'],
  'See recorded hours become estimated earnings. Review, approve, and export when you are ready.': ['Следете ја проценетата заработка според евидентираните часови. Прегледајте, одобрете и извезете кога сте подготвени.', 'Shihni pagën e përllogaritur sipas orëve të regjistruara. Shqyrtoni, miratoni dhe eksportoni kur të jeni gati.'],
  'Week overview': ['Неделен преглед', 'Përmbledhja e javës'],
  'Crew assigned': ['Доделен тим', 'Ekipi i caktuar'],
  'Mon': ['Пон', 'Hën'], 'Tue': ['Вто', 'Mar'], 'Wed': ['Сре', 'Mër'], 'Thu': ['Чет', 'Enj'], 'Fri': ['Пет', 'Pre'],
  'Production': ['Продукција', 'Produksioni'], 'Security': ['Обезбедување', 'Siguria'],
  'Shift ready': ['Смената е подготвена', 'Turni është gati'],
  'Everyone knows where to be.': ['Секој знае каде треба да биде.', 'Të gjithë e dinë ku duhet të jenë.'],
  'Preview check-in': ['Пробајте пријава', 'Provoni regjistrimin'],
  'Try again': ['Обидете се повторно', 'Provo përsëri'],
  'Check-in recorded': ['Пријавата е евидентирана', 'Regjistrimi u ruajt'],
  'You’re on the clock.': ['Вашето време се евидентира.', 'Koha juaj po regjistrohet.'],
  'Sample site code': ['Пример за код на локација', 'Shembull kodi të vendndodhjes'],
  'A working day, accounted for.': ['Работен ден со јасна евиденција.', 'Një ditë pune, e regjistruar.'],
  'Recorded hours': ['Евидентирани часови', 'Orët e regjistruara'],
  'Hourly rate': ['Саатница', 'Pagesa për orë'],
  'Review before you pay.': ['Прегледајте пред исплата.', 'Shqyrtoni përpara pagesës.'],
  'Work happens everywhere.': ['Работата се случува насекаде.', 'Puna ndodh kudo.'],
  'Keep everyone in the picture.': ['Сите нека бидат во тек.', 'Mbajini të gjithë të informuar.'],
  'From the first shift to the last check-out, the details stay connected.': ['Од првата смена до последната одјава, деталите остануваат поврзани.', 'Nga turni i parë deri te dalja e fundit, detajet mbeten të lidhura.'],
  'One team. Two clear views.': ['Еден тим. Два јасни прегледа.', 'Një ekip. Dy pamje të qarta.'],
  'Managers plan and review. Workers see their shifts, log their time, and know what they have earned.': ['Менаџерите планираат и прегледуваат. Работниците ги гледаат смените, го евидентираат времето и ја следат заработката.', 'Menaxherët planifikojnë dhe shqyrtojnë. Punonjësit shohin turnet, regjistrojnë orët dhe ndjekin pagën e tyre.'],
  'Clear hours. Clear boundaries.': ['Јасни часови. Јасни граници.', 'Orë të qarta. Kufij të qartë.'],
  'Set hourly rates and currencies. Review daily records with a 10-hour pay cap and keep overtime visible.': ['Поставете саатници и валути. Прегледајте ги дневните записи со ограничување од 10 платени часа и видлива прекувремена работа.', 'Caktoni pagesat për orë dhe monedhat. Shqyrtoni regjistrimet ditore me kufi pagese prej 10 orësh dhe orët shtesë të dukshme.'],
  'Speak your team’s language.': ['Зборувајте го јазикот на тимот.', 'Flisni gjuhën e ekipit tuaj.'],
  'English, Macedonian, and Albanian. Each person chooses the language that feels natural to them.': ['Англиски, македонски и албански. Секој го избира јазикот што му е најблизок.', 'Anglisht, maqedonisht dhe shqip. Secili zgjedh gjuhën që i përshtatet.'],
  'A little clarity goes a long way.': ['Малку јасност прави голема разлика.', 'Pak qartësi bën një ndryshim të madh.'],
  'Bring your people together. Give every shift a little more clarity.': ['Обединете ги вашите луѓе. Внесете повеќе јасност во секоја смена.', 'Bashkoni njerëzit tuaj. Sillni më shumë qartësi në çdo turn.'],
  'Back to top': ['Назад на почеток', 'Kthehu lart'],
};

export function landingText(text: string, language: Language) {
  return language === 'en-US' ? text : copy[text]?.[language === 'mk-MK' ? 0 : 1] ?? translateUi(text, language);
}
